### ISSUE TITLE
css url() path not relative to styles.css

### ISSUE THREAD

**Issue by metafarion** [mgsisk/inkblot#23]
I could be misunderstanding how this is supposed to work, but I feel like in the past, in a Wordpress theme stylesheet, I was able to use convenient paths like url("images/some-image.jpg") and this would work because the assumed path was relative to the location of styles.css.  In the current version of Inkblot, it seems that the assumed path is / and so my image path is much uglier ("wp-content/themes/themename/images/some-image.jpg")

When I examine the generated html, my stylesheet is included from http://domain.com/?inkblot_styles&ver=4.1 which probably explains this behavior, but I don't know how to change it, or if I even should.

**Comment by mgsisk** [comment]
That may be correct. Newer versions of Inkblot actually use a dynamically generated stylesheet as the main theme stylesheet which combines:

1. the theme `style.css` file
2. any customizations you've made with the WordPress Customizer, and
3. the `custom.css` file

into a single file that is, technically, loaded from the root of the site. I would recommend not trying to change that behavior; using something like `url('wp-content/themes/your-theme/images/some-image.jpg')` is the easier (if slightly uglier) way to handle this.

**Comment by mgsisk** [comment]
06e098ecd5142618335521712cd096f64c3b3440 actually corrects this; you should be able to link to images relative to the theme stylesheet now.
