### ISSUE TITLE
New update breaks site

### ISSUE THREAD

**Issue by milesfoxwood** [mgsisk/inkblot#26]
Hi,

For some reason the new update causes this error to come up:

Fatal error: Call to undefined function inkblot_theme_preview() in .../wp-content/themes/wc_ib_child/webcomic/home.php on line 13

I can't figure out why it's not working, any help would be appreciated.

Thank you,

Miles

**Comment by mgsisk** [comment]
Apologies for the trouble Miles. As that error alludes to, the `inkblot_theme_preview` function no longer exists in Inkblot. It looks like you're using a child theme; you may want to copy the new templates from Inkblot 4.1 into your child theme and tweak those (assuming you made any changes to the template files).

**Comment by milesfoxwood** [comment]
Yes, sorry, forgot to mention I was using a child theme with Inkblot. Thank you, that seems to have fixed it. 
Though for some reason my style sheet isn't working anymore. Is there something I should change to get it to recognize my style.css file?

**Comment by mgsisk** [comment]
That's a good question, actually. Inkblot's stylesheet is… sort of complicated, and I originally had a very lengthy explanation of what might be happening and how to fix it. Instead, I've pushed an update to the theme here on GitHub that will probably fix your issue. If you can, please download the latest version of Inkblot from here on GitHub and try it out.

As a reminder, theme modifications made in the Customizer override most `style.css` styles, even in child themes. If you want to make absolutely sure your custom CSS is being used you should put it in a `custom.css` file.

**Comment by mgsisk** [comment]
@milesfoxwood, ignore my previous comment about the `custom.css` file. You've forced me to actually think about this, and I'm trying to sort out a better way of handling child theme stylesheets. Thanks (honestly)!

**Comment by mgsisk** [comment]
Thanks again for forcing me to think this through @milesfoxwood. If you can, please download the latest version of Inkblot from here on GitHub and give it a try. You should put any custom CSS you have in your child theme's `style.css` file (I'm guessing that's where it already is), and everything will – hopefully – work as expected.

**Comment by milesfoxwood** [comment]
Okay, I did! Thanks for all your help!
