### ISSUE TITLE
Child theme sidebars

### ISSUE THREAD

**Issue by CAMorgan** [mgsisk/inkblot#29]
Hi, again!

I'm helping my friend make a child theme for inkblot. Her site is at http://e-orbits.com

My issue comes up during the Live Preview. Right now the site has a left and right sidebar on either side of the comic page. When I preview the child theme, everything is fine except that. The sidebars are below the comic, on either side of the news posts, instead of on either side of the comic image. Am I missing something?

**Comment by mgsisk** [comment]
Nope… from what I can tell, Live Preview just doesn't work well with child themes. I'd ignore the Live Preview and just use the Customizer after you've activated the child theme.

Child themes technically have their own set of theme modifications, but Live Preview appears to be loading the *parent* themes modifications by default. This would be great, but then it inconsistently updates the actual preview part of the Live Preview, and doesn't seem to save settings consistently either. For example, I tried this with a Twenty Fifteen child theme (to make sure that it wasn't just an Inkblot thing):

1. Activate Twenty Fifteen (the parent theme)
2. Go into the Customizer, select the Blue (or anything besides Default) Base Color Scheme, then click Save & Publish
3. Exit the Customizer, then click Live Preview on the Twenty Fifteen child theme
4. Note how the *parent* theme's color scheme is loaded (inconsistently) by default
5. Make a change to the theme – tweak the site title, for example – but **don't change the Base Color Scheme** (which should already have the parent theme's option selected)
6. Click Save & Publish to active the child theme
7. Note how the Base Color Scheme option was *completely ignored* in the Live Preview, despite selecting the parent theme's color scheme by default

This seems to work in the other direction, as well: making changes to the child theme and then previewing the parent theme will load the child themes modifications. I'm guessing this is just a rough spot in the Customizer that will be cleaned up in future WordPress updates

**Comment by CAMorgan** [comment]
Awesome. Thanks for the clarification!

**Comment by mgsisk** [comment]
Can you share the child theme you're using?

**Comment by CAMorgan** [comment]
I'm dumb. Had to select the option for placing the comic in the content section. Thanks again!
