### ISSUE TITLE
Updated to 4.2, styles gone

### ISSUE THREAD

**Issue by CAMorgan** [mgsisk/inkblot#30]
Hi again,

I just updated inkblot and now my child theme's styles aren't loading. My site is at http://tdugn.com/
Could I get a little help hunting down the issue? I had everything working with the previous update.

Edit: I just reuploaded the previous version so my site will work. I keep looking for the changelog for Inkblot to see what might be the issue but I can't seem to find it?

**Comment by mgsisk** [comment]
Inkblot 4.2 did away with the dynamic stylesheet, which may have been the problem (see 06e098ecd5142618335521712cd096f64c3b3440). You should just have to enqueue the parent themes stylesheet.
