### ISSUE TITLE
Missing Widgetized Areas

### ISSUE THREAD

**Issue by Mihari** [mgsisk/inkblot#32]
Webcomic Above and Below widgetized areas seem to be missing.

**Comment by mgsisk** [comment]
Ha ha, oops. Change lines 12 and 56 in `webcomic/image.php`:

```php
<?php inkblot_widgetized('webcomic-header'); ?>
…
<?php inkblot_widgetized('webcomic-footer'); ?>
```
to:
```php
<?php print inkblot_widgetized('webcomic-header'); ?>
…
<?php print inkblot_widgetized('webcomic-footer'); ?>
```

**Comment by gstrout** [comment]
The widgets @Mihari mentioned appear to be missing again: 
I notice the relevant file is now `webcomic/display.php` and lines 12 and 56 do currently read: 
`<?php print inkblot_widgetized('webcomic-header'); ?>`
and
`<?php print inkblot_widgetized('webcomic-footer'); ?>`
as you indicated. 

Is there something else missing?
