### ISSUE TITLE
Comic navigation not showing up under the comic

### ISSUE THREAD

**Issue by crunchypencil** [mgsisk/inkblot#33]
Hi. Love your template: just one problem I'm having--the navigation is set to show up ABOVE and BELOW the comic:
http://www.crunchypencil.com/cp6/
when I set the navigation to show up under AND over (Customize > Navigation), I just got 2 sets of navigation above the comic.

**Comment by mgsisk** [comment]
Thanks @crunchypencil! It looks like you may have sorted this one out; did you still have any issues?
