### ISSUE TITLE
Custom fields on taxonomies

### ISSUE THREAD

**Issue by metafarion** [mgsisk/inkblot#38]
I'm trying to use get_post_meta() to determine the value of the custom field webcomic_collection on my pages so I can have different main nav menus on each page.  This works fine for Pages, but not at all for single comics, archives, and other taxonomies as they have no webcomic_collection field.  Do you know of a way to set a custom field for those types of pages, or perhaps different post meta data I can latch on to?

**Comment by mgsisk** [comment]
You don't need to use a custom field; on those pages (single-webcomic, archives, taxonomy archives) Webcomic's [`get_webcomic_collection()`](https://github.com/mgsisk/webcomic/wiki/get_webcomic_collection) template tag should do the trick.
