### ISSUE TITLE
Inkblot child theme doesn't show up in Appearances > Themes

### ISSUE THREAD

**Issue by daniel-allington** [mgsisk/inkblot#47]
I created an Inkblot child theme that works perfectly offline using MAMP. Then I uploaded it to my site. I know it's there because I can get to the style.css file like this:
   http://[my url]wp-content/themes/[my child theme]/style.css
However, it doesn't show up in the list of installed themes at http://[my url]/wp-admin/themes.php so I can't activate it. I've tried everything I could find on the countless WordPress support threads about non-appearing themes (no there aren't any hyphens in the theme name, no I'm not using multisite, etc). So I tried searching for specific issues with Inkblot child themes and I found this:
   https://github.com/mgsisk/inkblot/issues/13
Could the above issue explain my problem? The current Inkblot style.css file makes no mention of any need to copy the whole style.css file when making a child theme, so I hope that the advice to do so relates only to earlier versions of Inkblot.
Please help.
With best wishes
D

**Comment by mgsisk** [comment]
Apologies for the trouble @daniel-allington. mgsisk/inkblot#13 wouldn't be the issue, unfortunately; more recent versions of Inkblot function just like other WordPress themes. Could you send me a copy of your child theme to test with? I've never heard of this particular issue, so it might be helpful if I can see exactly what you're working with.

Something you might also try – assuming you didn't start this way – is to use [Archimedes](github.com/mgsisk/archimedes) as a base for your Inkblot child theme. It includes only the bare-minimum code you need to get a child theme working, so it's largely a blank slate to work with.

**Comment by daniel-allington** [comment]
Well, it seems that non-appearance of themes is a frequent problem that can have many causes and because there's no error message (the themes just <em>don't appear</em>) it's very hard to debug.
This is only my second time creating a child theme, though, so I'm prepared to believe it's all down to something I've got wrong! I'm more than happy to send you a copy of the theme (which is not based on Archimedes, unfortunately - I didn't know about it). Thanks for offering to look at it. Shall I email it to the address in your profile?

**Comment by mgsisk** [comment]
That should work. Something else I thought of: if you haven't, double check the permissions on the hold themes folder (and the files in the folder). The folder should be either 755 or 777 (sometimes WordPress needs the broader permissions) and any files should be 644.

**Comment by daniel-allington** [comment]
Thanks very much indeed, Michael. I've sent it to you now.

Thanks also for the tip about permissions. I checked and got excited when I found that the style.css was not 644. But then I changed it and it still didn't appear on the Manage Themes page.

Given the number of different things that can cause WordPress to fail to notice a new theme, I really wish the people behind it would figure out a way to help users with debugging this issue.

**Comment by mgsisk** [comment]
Ah, sorry to hear @daniel-allington. I got your child theme… and of course my dev box saw it immediately, so I'm still at a loss for what might be tripping it up. Just for kicks you might try:

1. setting `style.css` to 777 and see if that does anything. You shouldn't have to do this, and even if it works I wouldn't recommend leaving the permissions at 777 (644 really ought work; if 777 *does* work but 644 doesn't this might point to some weird server issue).
2. removing the tabs in the meta info of `style.css`. This *really* shouldn't affect anything, but since nothing else has worked it might be worth trying just normal spaces between `:` and the values.

**Comment by daniel-allington** [comment]
Thanks very much @mgsisk! But no joy. The tabs are now spaces and I temporarily changed the permissions on style.css to 777, but neither of these things made a difference. Also the helpdesk people at my hosting service weren't able to say anything beyond 'I was still not able to get this new child theme to show up, there is likely an issue in the style.css or one of the php files in that theme'. Except that if there was an issue with the css or php the error would presumably be replicable on your dev box. Argh.

I'll try the WordPress support forums now! Thanks again for your help.

**Comment by mgsisk** [comment]
No problem @daniel-allington; sorry I couldn't help out more. Let me know if you find any solution to this.

**Comment by daniel-allington** [comment]
Michael, I tried making my theme again, starting with the Archimedes files in the hope that this will make a difference. I'm only just getting to grips with the most basic aspects of CSS and PHP. I have a couple of questions.

The first is that it says this in functions.php :

======
add_action('wp_enqueue_scripts', 'archimedes_wp_enqueue_scripts');
add_action('after_setup_theme', 'inkblot_after_setup_theme');
======

Should the second of those read 'archimedes_after_setup_theme' rather than 'inkblot_after_setup_theme'? If not, I can't currently see when the archimedes_after_setup_theme() function defined in that file is called.

The second is that I'm not sure I need the archimedes_after_setup_theme() function anyway, as I don't think I have a need for a .pot file - can I just get rid of that function and the l10n folder?
