### ISSUE TITLE
Webcomics Archive template not working?

### ISSUE THREAD

**Issue by ykyu** [mgsisk/inkblot#70]
Figured I'd post in the correct repository even if the Webcomic one seems far more active. 

I'm certain the Webcomic Archive template is supposed to be plug-n-play, but I haven't been able to display anything other than the default page contents. There isn't any documentation for Inkblot or this template page specifically that I've found, so the expected behaviour is honestly just a guess.

### Expected Behavior
In addition to whatever Page content there is, Pages set to the "Webcomic Archive" template should display thumbnails of all Storylines and Comic Pages from the Collection selected under "Webcomic Settings" for the page.

### Current Behavior
Page contents are shown, but instead of thumbnails to comic pages, there is only a bulleted link to the default archive page for the selected Collection.

### Context
I'm hoping/assuming the "Webcomic Archive" page template will help get around the "posts per page" issue of the default archives, which uses the "posts per page" of the overall WP installation by default and can be annoying if you, say, only want 1 blog entry on the front page, but have 100+ pages of comic archive you want to display on a single archive page (because otherwise what's the point, haha). You can hardcode override the "posts per page" setting in /webcomics/collection.php but that seems inelegant.

Currently though, the "Webcomic Archive" page doesn't seem to work as intended at all?

### Example

Website isn't live, but below are screenshots of various settings.

### Environment
- Most recent build of Inkblot
- Webcomic 5.0.5
- WordPress 4.9.6

![image](https://user-images.githubusercontent.com/15319435/40626191-b9221868-626b-11e8-9dda-bae581c02e64.png)
![image](https://user-images.githubusercontent.com/15319435/40626209-db9ed3a4-626b-11e8-8f2c-4173de2b4e20.png)
![image](https://user-images.githubusercontent.com/15319435/40626223-f0868d2a-626b-11e8-8957-ff21017ec15f.png)

**Comment by mgsisk** [comment]
Hey @ykyu, thanks for posting in the correct repo, and apologies for the trouble. Can you share a screenshot of the settings in the **Template Options** metabox on the Add/Edit Page screen? That's what Inkblot actually uses to configure the display of it's Webcomic Archive template.

The templates available in the **Webcomic Settings** metabox are (somewhat unhelpfully) not currently supported by Inkblot, unfortunately; it needs to be updated to work with Webcomic 5's new integration settings.

**Comment by ykyu** [comment]
OH, wow, I feel silly. I didn't even see the Template Options box since the header was collapsed by default for some reason. Setting thumbnail options has the page work as intended, just needs some better styling. Thanks for your help!
